server:
  port: 9091

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: elvin
    password: 12345
  application:
    name: PAYMENT-SERVICE
  zipkin:
    base-url: http://localhost:9411/

logging:
  file:
    name: C:/Users/Hp/Desktop/logs/microservices.log
