server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:orderdb
    username: elvin
    password: 12345
  application:
    name: ORDER-SERVICE

ms:
  payment:
    url: http://PAYMENT-SERVICE/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
